[package]
name = "fsm_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0", features = ["parsing", "proc-macro", "extra-traits"]}
quote = "1.0"
proc-macro2 = "1.0.24"